enum FactionNames3 {
  'wh2_dlc09_tmb_tomb_kings' = 'Tomb Kings',
  'wh2_dlc11_cst_vampire_coast' = 'Vampire Coast',
  'wh2_main_def_dark_elves' = 'Dark Elves',
  'wh2_main_hef_high_elves' = 'High Elves',
  'wh2_main_lzd_lizardmen' = 'Lizardmen',
  'wh2_main_skv_skaven' = 'Skaven',
  'wh3_main_cth_cathay' = 'Grand Cathay',
  'wh3_main_dae_daemons' = 'Demons of Chaos',
  'wh3_main_kho_khorne' = 'Khorne',
  'wh3_main_ksl_kislev' = 'Kislev',
  'wh3_main_nur_nurgle' = 'Nurgle',
  'wh3_main_ogr_ogre_kingdoms' = 'Ogre Kingdoms',
  'wh3_main_sla_slaanesh' = 'Slaanesh',
  'wh3_main_tze_tzeentch' = 'Tzeentch',
  'wh_dlc03_bst_beastmen' = 'Beastmen',
  'wh_dlc05_wef_wood_elves' = 'Wood Elves',
  'wh_dlc08_nor_norsca' = 'Norsca',
  'wh_main_brt_bretonnia' = 'Brettonia',
  'wh_main_chs_chaos' = 'Warriors of Chaos',
  'wh_main_dwf_dwarfs' = 'Dwarfs',
  'wh_main_emp_empire' = 'The Empire',
  'wh_main_grn_greenskins' = 'Greenskins',
  'wh_main_vmp_vampire_counts' = 'Vampire Counts',
}

enum FactionNames2 {
  'wh2_dlc09_tmb_tomb_kings' = 'Tomb Kings',
  'wh2_dlc11_cst_vampire_coast' = 'Vampire Coast',
  'wh2_main_def_dark_elves' = 'Dark Elves',
  'wh2_main_hef_high_elves' = 'High Elves',
  'wh2_main_lzd_lizardmen' = 'Lizardmen',
  'wh2_main_skv_skaven' = 'Skaven',
  'wh_dlc03_bst_beastmen' = 'Beastmen',
  'wh_dlc05_wef_wood_elves' = 'Wood Elves',
  'wh_dlc08_nor_norsca' = 'Norsca',
  'wh_main_brt_bretonnia' = 'Brettonia',
  'wh_main_chs_chaos' = 'Warriors of Chaos',
  'wh_main_dwf_dwarfs' = 'Dwarfs',
  'wh_main_emp_empire' = 'The Empire',
  'wh_main_grn_greenskins' = 'Greenskins',
  'wh_main_vmp_vampire_counts' = 'Vampire Counts',
}

export { FactionNames2, FactionNames3 };
